name: Lessons-dev MyBinder Test

channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - gdal
  - rise
  - fiona  
  - rasterio
  
  - pip:
    - jupyter_contrib_nbextensions
    - jupyterlab_scenes
    - numpy
    - pandas
    - utm
    - geopandas
    - shapely
    - folium
    - pysal
    - matplotlib
    - matplotlib_scalebar
    - osmnx
    - earthpy
    - ipyleaflet
# presentation:
#   - pip:
#     - jupyter_contrib_nbextensions
#     - RISE
#   - postBuild
#     - jupyter contrib nbextension install --user
#     - jupyter nbextension enable widgetsnbextension  --py --user
#     - jupyter nbextension enable python-markdown/main  --py --user
#     - jupyter-nbextension install rise --py --user
#     - jupyter-nbextension enable rise  --py --user 
